name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  native_tests:
    name: ${{ matrix.variants.os }} / ${{ matrix.variants.config }} / Library
    strategy:
      fail-fast: false
      matrix:
        variants:
          - {os: "windows-2022",  config: Debug}
          - {os: "ubuntu-22.04",  config: Debug}
          - {os: "macos-13",      config: Debug}
    runs-on: ${{ matrix.variants.os }}
    steps:
    - uses: actions/checkout@v4
    - run: cmake -S. -B build -DTLSH_BUILD_WITH_ASAN=ON -DTLSH_BUILD_TESTS=ON -DTLSH_BUILD_BINDINGS=OFF
    - run: cmake --build ./build --config ${{ matrix.variants.config }}
    - run: ctest --progress --build-config ${{ matrix.variants.config }} --test-action test --test-dir ./build

  binding_tests:
    name: ${{ matrix.os }} / Python${{ matrix.py }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
        py: ['3.8', '3.9', '3.10', '3.11', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5.1.0
      with:
        python-version: ${{ matrix.py }}
    - run: python -m pip install --user --upgrade .[tests]
    - run: python -m pytest -vv python/tests